
CREATE TABLE OBJECTCONFIG
(
  ID            	NUMBER(19)   NOT NULL,
  VERSION       	TIMESTAMP(6) NOT NULL,
  LOGIN         	VARCHAR2(32),
  PROFILE       	VARCHAR2(32),
  APPLICATION_NAME 	VARCHAR2(32),
  OBJECT_TYPE   	VARCHAR2(8),
  OBJECT_ID     	VARCHAR2(256),
  CONFIGURATION 	CLOB,
  PRIMARY KEY (ID)
);

commit;
