package drools

import com.linedata.ekip.std.services.rulesengine.service.impl.KnowledgeBaseResponse;
import com.linedata.ekip.std.services.rulesengine.bean.RulesContext;

function boolean evaluateResult(Object id)
{
	  	boolean res = true;
	  	if(id instanceof Long)
	  	{
	  		res = ((Long) id) == 3;
	  	}
	  	else if (id instanceof Integer)
	  	{
	  		res = ((Integer) id) == 3;
	  	}
	  	
		return res;
}


rule "isId2"
when
	RulesContext(id : screenContextRulesParam.entity.mappedAttributes['id'])
    $response: KnowledgeBaseResponse()
    eval(evaluateResult(id))
then
	$response.setVerified(true);
end
